# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
# Added following addional addional container by Chinthaka Deshapriya <chinthaka@ceee.dev>
# NPMPlus as the reverse proxy - optional
# Duplicati as the backup tool - optional
# Stalwart as the mail server  - optional

version: '2'
services:
  postgresql: 
    image: docker.io/bitnami/postgresql:16
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_mastodon
      - POSTGRESQL_USERNAME=bn_mastodon
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
  
  redis:
    image: docker.io/bitnami/redis:7.0
    volumes:
      - 'redis_data:/bitnami/redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
 
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:8
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
    environment:
      - ELASTICSEARCH_ENABLE_SECURITY=true
      - ELASTICSEARCH_SKIP_TRANSPORT_TLS=true
      - ELASTICSEARCH_ENABLE_REST_TLS=false
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
  
  mastodon:
    image: docker.io/bitnami/mastodon:4
    ports:
      - 80:3000
    volumes:
      - 'mastodon_data:/bitnami/mastodon'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MASTODON_MODE=web
      - MASTODON_ADMIN_USERNAME=admin
      - MASTODON_ADMIN_PASSWORD=${MASTODON_ADMIN_PASSWORD}
      - MASTODON_DATABASE_PASSWORD=${POSTGRESQL_PASSWORD}
      - MASTODON_WEB_DOMAIN=${MASTODON_WEB_DOMAIN}
      - MASTODON_MODE=streaming
      - MASTODON_ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
  
  mastodon-sidekiq:
    image: docker.io/bitnami/mastodon:4
    volumes:
      - 'mastodon_data:/bitnami/mastodon'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MASTODON_MODE=sidekiq
      - MASTODON_DATABASE_PASSWORD=${POSTGRESQL_PASSWORD}
      - MASTODON_ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}

  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - 'minio_data:/bitnami/minio/data'

volumes:
  postgresql_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local
  mastodon_data:
    driver: local
